# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:

trigger:
- main
- test

pool:
  vmImage: ubuntu-latest

variables:
- ${{ if eq(variables['build.SourceBranchName'], 'main') }}:
  - group: 'mc-custom-activity-prod-env-variable-group'
  - name: CA_NAME
    value: 'PROD'
- ${{ if eq(variables['build.SourceBranchName'], 'test') }}:
  - group: 'mc-custom-activity-uat-env-variable-group'
  - name: CA_NAME
    value: 'UAT'

jobs:
- job: Build_Test
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.0.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run lint
        if [ $? -ne 0 ]; then
        exit 1
        fi
        npm run test
        npm prune --production
      displayName: 'npm install, lint, and test'

- job: Package_Deploy
  dependsOn: Build_Test
  steps:
    - task: AWSShellScript@1
      displayName: Package
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION_NAME)
        regionName: $(AWS_REGION)
        scriptType: 'inline'
        disableAutoCwd: true
        inlineScript: |
          sam build --use-container
    - task: AWSShellScript@1
      displayName: Deploy Infrastructure
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION_NAME)
        regionName: $(AWS_REGION)
        scriptType: "inline"
        inlineScript: |
          sam deploy \
          --force-upload \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --stack-name $(AWS_STACK_NAME) \
          --s3-bucket $(AWS_BUCKET_NAME) \
          --capabilities CAPABILITY_IAM \
          --region $(AWS_REGION) \
          --parameter-overrides \
          JwtTokenSecretMC=$(MC_JWT_SECRET) \
          SmsApiGatewayKey=$(SMS_GATEWAY_KEY) \
          SmsApiConcurrency=$(SMS_API_CONCURRENCY) \
          SmsBulkApiConcurrency=$(SMS_BULK_API_CONCURRENCY) \
          SmsBulkApiBatchSize=$(SMS_BULK_API_BATCH_SIZE) \
          EndpointUrlSMS=$(ENDPOINT_URL_SMS) \
          EndpointBulkUrlSMS=$(ENDPOINT_BULK_URL_SMS)
    - task: AWSShellScript@1
      displayName: Get & Replace API URl
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION_NAME)
        regionName: $(AWS_REGION)
        scriptType: "inline"
        inlineScript: |
          apiUrl=$(aws cloudformation describe-stacks --stack-name $(AWS_STACK_NAME) --region $(AWS_REGION) \
          --query "Stacks[0].Outputs[?OutputKey=='ExecuteApiUrl'].OutputValue" --output text)
          sed -i "s|{{ API_ENDPOINT }}|$apiUrl|g" public/config.json
          sed -i "s|{{ CA_NAME }}|$(CA_NAME)|g" public/config.json
    - task: AWSShellScript@1
      displayName: Deploy Public Folder
      inputs:
        awsCredentials: $(AWS_SERVICE_CONNECTION_NAME)
        regionName: $(AWS_REGION)
        scriptType: "inline"
        inlineScript: |
          aws s3 sync ./public s3://$(AWS_BUCKET_NAME_PUBLIC) \
          --region $(AWS_REGION) \
          --acl public-read \
          --size-only
