AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MarketingCloudCustomActivityMultiChoice

  SAM Template for MultiChoice Marketing Cloud Custom Activity

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs14.x
    Architectures: 
      - x86_64
    MemorySize: 128
    EventInvokeConfig: 
      MaximumEventAgeInSeconds: 60
      MaximumRetryAttempts: 2
Parameters:
    JwtTokenSecretMC:
        Description: 'Marketing Cloud JWT Token'
        Type: 'String'
        #Type: 'AWS::SSM::Parameter::Value<String>'
        #Default: 'JwtTokenSecretMC'
    SmsApiGatewayKey:
        Description: 'API SMS Gateway Key'
        Type: 'String'
        #Type: 'AWS::SSM::Parameter::Value<String>'
        #Default: 'SmsApiGatewayKey'
    SmsBulkApiGatewayKey:
        Description: 'API SMS Gateway Key'
        Type: 'String'
        #Type: 'AWS::SSM::Parameter::Value<String>'
        #Default: 'SmsBulkApiGatewayKey'
    EndpointUrlSMS:
        Description: 'API SMS Gateway Endpoint URL'
        Type: 'String'
        #Type: 'AWS::SSM::Parameter::Value<String>'
        #Default: 'EndpointUrlSMS'
    EndpointBulkUrlSMS:
        Description: 'BULK API SMS Gateway Endpoint URL'
        Type: 'String'
        #Type: 'AWS::SSM::Parameter::Value<String>'
        #Default: 'EndpointBulkUrlSMS'
    SmsApiConcurrency:
        Description: 'API SMS Gateway Concurrency'
        Type: 'String'
        #Type: 'AWS::SSM::Parameter::Value<String>'
        #Default: 'SmsApiConcurrency'
    SmsBulkApiConcurrency:
        Description: 'BULK API SMS Gateway Concurrency'
        Type: 'String'
        #Type: 'AWS::SSM::Parameter::Value<String>'
        #Default: 'SmsBulkApiConcurrency'
    SmsBulkApiBatchSize:
        Description: 'BULK API SMS Gateway Batch Size'
        Type: 'String'
        #Type: 'AWS::SSM::Parameter::Value<String>'
        #Default: 'SmsBulkApiBatchSize'
Resources:
  HttpSmsMcApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefaultRouteSettings:
        ThrottlingBurstLimit: 750 #Set to 750 conccurent requests
        ThrottlingRateLimit: 1500 #Set to 2000 qps => 5.4m by hour
  SmsDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-SmsDeadQueue'
      ReceiveMessageWaitTimeSeconds: 20
  SmsBulkDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-SmsBulkDeadQueue'
      ReceiveMessageWaitTimeSeconds: 20
  SmsSmrtBulkDeadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-SmsSmrtBulkDeadQueue'
      ReceiveMessageWaitTimeSeconds: 20
  SmsApiQueue: 
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-SmsApiQueue'
      VisibilityTimeout: 60
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt: 
            - 'SmsDeadQueue'
            - 'Arn'
        maxReceiveCount: 2
  SmsBulkApiQueue: 
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-SmsBulkApiQueue'
      VisibilityTimeout: 60
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt: 
            - 'SmsBulkDeadQueue'
            - 'Arn'
        maxReceiveCount: 2
  SmsBulkSmrtApiQueue: 
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-SmsBulkSmrtApiQueue'
      VisibilityTimeout: 60
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt: 
            - 'SmsSmrtBulkDeadQueue'
            - 'Arn'
        maxReceiveCount: 2
  ExecuteEntryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-ExecuteEntryFunction'
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - 'lambda:InvokeAsyncs'
                - 'lambda:InvokeFunction'
                - 'sqs:SendMessage'
              Resource:
                - '*'
      Environment:
        Variables:
          MCSecret: !Ref JwtTokenSecretMC
          smsQueueUrl: !Ref SmsApiQueue
          smsQueueBulkUrl: !Ref SmsBulkApiQueue
          smsSmrtQueueBulkUrl: !Ref SmsBulkSmrtApiQueue
      CodeUri: lambdas/executeEntry/
      Handler: app.lambdaHandler
      Layers:
              - !Ref JsonWebTokenLayer
      Events:
        ExecuteEntry:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpSmsMcApi
            Path: /execute
            Method: POST
            TimeoutInMillis: 20000
  PublishEntryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-PublishEntryFunction'
      Environment:
        Variables:
          MCSecret: !Ref JwtTokenSecretMC
      CodeUri: lambdas/publishEntry/
      Handler: app.lambdaHandler
      Layers:
              - !Ref JsonWebTokenLayer
      Events:
        PublishEntry:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpSmsMcApi
            Path: /publish
            Method: POST
            TimeoutInMillis: 20000
        ValidateEntry:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpSmsMcApi
            Path: /validate
            Method: POST
            TimeoutInMillis: 20000
        SaveEntry:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpSmsMcApi
            Path: /save
            Method: POST
            TimeoutInMillis: 20000
  CallSmsApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CallSmsApiFunction'
      Timeout: 15
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - 'sqs:ReceiveMessage'
              Resource:
                - '*'
      Environment:
        Variables:
          SmsApiGatewayKey: !Ref SmsApiGatewayKey
          EndpointUrlSMS: !Ref EndpointUrlSMS
      CodeUri: lambdas/callSmsApi/
      Handler: app.lambdaHandler
      ReservedConcurrentExecutions: !Ref SmsApiConcurrency
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 300
        MaximumRetryAttempts: 1
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: 
              Fn::GetAtt: 
                - 'SmsApiQueue'
                - 'Arn'
            MaximumBatchingWindowInSeconds: 10
            BatchSize: 1
  CallSmsBulkApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CallSmsBulkApiFunction'
      Timeout: 15
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - 'sqs:ReceiveMessage'
              Resource:
                - '*'
      Environment:
        Variables:
          SmsBulkApiGatewayKey: !Ref SmsBulkApiGatewayKey
          EndpointBulkUrlSMS: !Ref EndpointBulkUrlSMS
      CodeUri: lambdas/callSmsBulkApi/
      Handler: app.lambdaHandler
      ReservedConcurrentExecutions: !Ref SmsBulkApiConcurrency
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 300
        MaximumRetryAttempts: 1
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: 
              Fn::GetAtt: 
                - 'SmsBulkApiQueue'
                - 'Arn'
            MaximumBatchingWindowInSeconds: 20
            BatchSize: !Ref SmsBulkApiBatchSize
  CallSmsBulkApiSmrtFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CallSmsBulkApiSmrtFunction'
      Timeout: 15
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - 'sqs:ReceiveMessage'
              Resource:
                - '*'
      Environment:
        Variables:
          SmsBulkApiGatewayKey: !Ref SmsBulkApiGatewayKey
          EndpointBulkUrlSMS: !Ref EndpointBulkUrlSMS
      CodeUri: lambdas/callSmsBulkApiSmrt/
      Handler: app.lambdaHandler
      ReservedConcurrentExecutions: !Ref SmsBulkApiConcurrency
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 300
        MaximumRetryAttempts: 1
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: 
              Fn::GetAtt: 
                - 'SmsBulkSmrtApiQueue'
                - 'Arn'
            MaximumBatchingWindowInSeconds: 20
            BatchSize: !Ref SmsBulkApiBatchSize
  JsonWebTokenLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: web-token-dependencies
            Description: Dependencies for sam app [web-token]
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs6.10
              - nodejs8.10
              - nodejs14.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain

Outputs:
  ExecuteApiUrl:
    Description: 'API Gateway endpoint URL for Prod stage for Execute function'
    Value: !Sub 'https://${HttpSmsMcApi}.execute-api.${AWS::Region}.amazonaws.com/'
  ExecuteEntryFunction:
    Description: 'Lambda Function called by Executed route'
    Value: !GetAtt ExecuteEntryFunction.Arn
  ExecuteEntryFunctionIamRole:
    Description: 'Implicit IAM Role created for Execute function'
    Value: !GetAtt ExecuteEntryFunctionRole.Arn
  PublishEntryFunction:
    Description: 'Lambda Function called by Save, Validate and Publish routes'
    Value: !GetAtt PublishEntryFunction.Arn
  PublishEntryFunctionIamRole:
    Description: 'Implicit IAM Role created for Publish function'
    Value: !GetAtt PublishEntryFunctionRole.Arn
  CallSmsApiFunction:
    Description: 'Call SMS API Lambda Function ARN'
    Value: !GetAtt CallSmsApiFunction.Arn
  CallSmsApiFunctionIamRole:
    Description: 'Implicit IAM Role created for CallSmsApi function'
    Value: !GetAtt CallSmsApiFunctionRole.Arn
  CallSmsBulkApiFunction:
    Description: 'Call SMS Bulk API Lambda Function ARN'
    Value: !GetAtt CallSmsBulkApiFunction.Arn
  CallSmsBulkApiFunctionIamRole:
    Description: 'Implicit IAM Role created for CallSmsBulkApi function'
    Value: !GetAtt CallSmsBulkApiFunctionRole.Arn    
  SmsApiQueue:
    Description: 'SMS API Queue ARN'
    Value: !GetAtt SmsApiQueue.Arn
  SmsBulkApiQueue:
    Description: 'SMS Bulk API Queue ARN'
    Value: !GetAtt SmsBulkApiQueue.Arn    
  SmsBulkSmrtApiQueue:
    Description: 'SMS Bulk Smart API Queue ARN'
    Value: !GetAtt SmsBulkSmrtApiQueue.Arn   
  SmsDeadQueue:
    Description: 'SMS API Dead Queue ARN'
    Value: !GetAtt SmsDeadQueue.Arn
  SmsBulkDeadQueue:
    Description: 'SMS Bulk API Dead Queue ARN'
    Value: !GetAtt SmsBulkDeadQueue.Arn
  SmsSmrtBulkDeadQueue:
    Description: 'SMS Bulk API Dead Queue ARN'
    Value: !GetAtt SmsSmrtBulkDeadQueue.Arn
