AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  testAntoineSamConsol

  Sample SAM Template for testAntoineSamConsol
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs14.x
    Architectures:
        - x86_64
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Environment:
        Variables:
          mcSecret: 'shhhhh'
      CodeUri: lambdas/hello-world/
      Handler: app.lambdaHandler
      Layers:
              - !Ref JsonWebTokenLayer
      Events:
        HelloWorld:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: any
  CallSmsApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Environment:
        Variables:
          SmsApiGatewayKey: '08e743a0-0d22-4b27-aeb5-9937cb5e1383'
      CodeUri: lambdas/callSmsApi/
      Handler: app.lambdaHandler           
  JsonWebTokenLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: web-token-dependencies
            Description: Dependencies for sam app [web-token]
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs6.10
              - nodejs8.10
              - nodejs14.x    
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain

Outputs:
  # ServerlessHttpApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
