env:
  STACK_NAME: MC-CA-API
  S3_BUCKET_NAME: testsiteantoine
  S3_BUCKET_NAME_PUBLIC: 	testsiteantoineform
  AWS_REGION: af-south-1
  AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MC_JWT_SECRET: ${{ secrets.MC_JWT_SECRET }}
  SMS_GATEWAY_KEY: ${{ secrets.SMS_GATEWAY_KEY }}
  SMS_API_CONCURRENCY: ${{ secrets.SMS_API_CONCURRENCY }}
  ENDPOINT_URL_SMS: ${{ secrets.ENDPOINT_URL_SMS }}

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run test
      - run: npm prune --production
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: |
          sam deploy --force-upload --no-confirm-changeset --no-fail-on-empty-changeset \
          --stack-name ${{ env.STACK_NAME }} --s3-bucket ${{ env.S3_BUCKET_NAME }} \
          --capabilities CAPABILITY_IAM --region ${{ env.AWS_REGION }} \
          --parameter-overrides \
          JwtTokenSecretMC=$(MC_JWT_SECRET) \
          SmsApiGatewayKey=$(SMS_GATEWAY_KEY) \
          SmsApiConcurrency=$(SMS_API_CONCURRENCY) \
          EndpointUrlSMS=$(ENDPOINT_URL_SMS)

      - run:  |
          aws s3 sync ./public s3://${{ env.S3_BUCKET_NAME_PUBLIC }} --region ${{ env.AWS_REGION }} \
          --acl public-read --size-only
